# permissions to do viewer calculations.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: calculation-viewer-role
rules:
- apiGroups:
  - fizzbuzz.my.domain
  resources:
  - calculations
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - fizzbuzz.my.domain
  resources:
  - calculations/status
  verbs:
  - get
