# permissions to do viewer queries.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: query-viewer-role
rules:
- apiGroups:
  - fizzbuzz.my.domain
  resources:
  - queries
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - fizzbuzz.my.domain
  resources:
  - queries/status
  verbs:
  - get
