# permissions to do edit queries.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: query-editor-role
rules:
- apiGroups:
  - fizzbuzz.my.domain
  resources:
  - queries
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - fizzbuzz.my.domain
  resources:
  - queries/status
  verbs:
  - get
  - patch
  - update
